"""add meet_link to calendar_event_drafts

Revision ID: 2336f6ca69df
Revises: 436dae342445
Create Date: 2026-06-30 14:23:43.738275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2336f6ca69df'
down_revision: Union[str, None] = '436dae342445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event_drafts', sa.Column('meet_link', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event_drafts', 'meet_link')
    # ### end Alembic commands ###
