"""add reminder_sent to calendar_event_drafts

Revision ID: 436dae342445
Revises: 63eb6d1f9a3a
Create Date: 2026-06-29 05:06:22.498499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436dae342445'
down_revision: Union[str, None] = '63eb6d1f9a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event_drafts', sa.Column('reminder_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event_drafts', 'reminder_sent')
    # ### end Alembic commands ###
