"""add_timezone_to_user_and_calendar_event

Revision ID: 782a049e2fe3
Revises: 2336f6ca69df
Create Date: 2026-07-01 21:53:35.201814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782a049e2fe3'
down_revision: Union[str, None] = '2336f6ca69df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event_drafts', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('calendar_event_drafts', 'timezone')
    # ### end Alembic commands ###
